# Generated by Django 3.1.2 on 2020-10-22 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=60, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('designation', models.CharField(choices=[('student', 'Student'), ('scholar', 'Scholar'), ('prefect', 'Prefect'), ('bursar', 'Bursar')], max_length=60)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('notpaid', 'Not Paid'), ('paid', 'Paid')], default='notpaid', max_length=20)),
                ('auth_user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mlm_user_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=60, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=60, null=True)),
                ('level', models.CharField(max_length=5)),
                ('parent', models.ForeignKey(db_column='parent_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_hierarchy_parent_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_hierarchy_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mlm_user_hierarchy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('last_updated_on', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=60, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted')], default='invited', max_length=20)),
                ('email', models.CharField(max_length=255)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mlm_invite',
                'managed': True,
            },
        ),
    ]
