# Generated by Django 3.1.2 on 2020-10-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201024_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhierarchy',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='invited', max_length=20),
        ),

    ]
