# Generated by Django 3.1.2 on 2020-10-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201025_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhierarchy',
            name='level',
        ),
    ]
