# Generated by Django 3.1.2 on 2020-10-26 04:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_userhierarchy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hr_tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
