# Generated by Django 3.1.2 on 2020-10-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_hr_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hr_tree',
            field=models.JSONField(null=True),
        ),
    ]
