<template>
  <v-container>
    <h1 class="main_text">TERMS OF SERVICE FOR CREATORS</h1>
    <h3>1. Introduction</h3>
    <p>
      Thank you for your interest in Trenstop Global Inc (“Company,” “We,” “Us,” or “Our”)
owner and operator of the website located at
      <a
        href="https://www.excluzeev.com"
      >www.excluzeev.com</a> (“Website” or “Site”)
and the Excluzeev mobile application (“App”). The Website, Site, and App are hereinafter
collectively referred to as “Excluzeev” or “Service”. The Service enables fans/ followers
to gain access to content created by Creators from around the world by subscribing to
one or more of channels offered by a Creator. <br>
These Terms of Service including our Privacy Policy (collectively “Terms” or
“Agreement”) constitute a binding agreement between you either an individual, group or
entity (the “Creator,” “User,” “You,” or “Your”) and the Company regarding your use of the
Service. <br>
We reserve the right to update these Terms at any time without giving any prior notice to
you. When we make any material changes to these Terms, we will notify you by updating
the ‘last updated date’ at the top of this page. Your continued use of the Service will
constitute an express acceptance of such changes by you.
    </p>
    <br>
    <h3>2.Additional Terms</h3>
    <p>
      Some areas, features and services offered by the Company may have additional Terms
of Service applicable. When you make use of those areas, features and services, you
agree to abide by such additional terms and such additional terms are deemed to be
incorporated into this Agreement. Please take note - in the event of any conflict between
these terms and the terms governing your use of a specific feature or service offered by
the Company, the latter terms will take precedence with respect to your use of that
service.
    </p>
    <h3>3.Summary</h3>
    <p>Here is a summary of some important provisions covered in this Agreement. Please note
that this summary is only provided for your convenience and does not replace your
obligation to read and understand this Agreement fully. You should always read the full
Agreement before accessing the Service:</p>
    <ul>
      <li>You must be at least eighteen years of age to enter into this Agreement with the Company;</li> <br>
      <li>You are required to provide your banking details at the time of account creation to
enable your fans to subscribe to your channel and for you to receive income
generated by your content;</li> <br>
      <li>You agree to pay the service fee and transaction fee on all payments processed
through Excluzeev;</li>
<br>
      <li>All personal information you provide us during account registration will be
governed by our Privacy Policy. Please review our Privacy Policy before you sign
up for a Creator account;</li>
    <br>
      <li>All payments are collected and processed by Stripe payment gateway;</li>
    <br>
      <li>Creators have specific obligations which are specified in article 7 of this
Agreement. Any violation of these obligations will amount to a material breach of
this Agreement;</li>
    <br>
      <li>You are solely responsible for maintaining the confidentiality of your account sign
in details; </li> <br>
<li>
Copyright violation is a serious offence, and we do not condone such behaviour.
You agree that you will not use, upload, share or make available any content
through Excluzeev that violates another person’s copyright; </li> <br>
<li> The Company is offering the Services to you subject to certain disclaimers of
warranties and limitation of its liability, please carefully review these provisions
and if you do not agree with them, please do not use our Services.</li>
    </ul>
    <h3>4.Key Terms</h3>
    <p>Unless expressly stated otherwise, the following words shall hold the meaning as described hereunder:</p>
    <p>
      <b>"Creator"</b> - A User who registers for a Creator account on Excluzeev.
    </p>
    <br>
<p> <b>“Subscriber,” “Fan,” or “Follower”</b> - refers to a User who subscribes for a specific
channel offered by the Creator on Excluzeev.</p>
<br>
<p>
      <b>“Content”</b> - Any audio/video content including any live video streams and chats offered
by the Creator to his/her subscribers/fans/followers on Excluzeev.
    </p> <br>
<p>
      <b>“User”</b> - refers to all Users of the Service offered by the Company whether registered or
unregistered.
    </p> <br>
    <p> 
      <b>“Content license”</b> - refers to the license that the Creator decides to grant his or her subscriber to access the content on his/her channel provided such license does not violate any terms of the licensing agreement between the Creator and the Company.
    </p>
    <p>
      <b>“Parties”</b> - collectively refers to Creator, Community Members or Users when interacting with each other through the Service.
    </p>
    <p>
      <b>“Service/s”</b> - include but is not limited to the website, app and all software features and functionality offered by the Company to its users such as content posting, uploading, live video streaming and chat functionality.
    </p>
    <p>
     <b> “Subscription fees”</b> - refers to the monthly channel fee listed by the Creator that a
Subscriber would pay to access the Content.
    </p>
    <p>
      <b>“Service fees”</b> - a fixed fee of 5% will be charged by the Company to the Creator on all income earned by the Creator through Ecluzeev.
    </p>
    <p>
      <b>“Transaction fees”</b> - refers to Stripe transaction fees of 0.25% charged and deducted from the Creator on all income earned by the Creator through Excluzeev.
    </p>
<br>
    <p>
      <b>“Excluzeev Live”</b> - refers to the live video streaming service offered by the Company to Creators as a marketing tool to connect with their community members. All community members of Creator’s channels get access to Creator’s Excluzeev live broadcast.
    </p>
    <br>




    
    <h3>5.Eligibility</h3>
    <p>
      You must be at least eighteen (18) years of age to sign up for a Creator account on
Excluzeev, and you must have the capacity to enter into a legally binding Agreement in
your country or state of residence.
      <p>
    
      PLEASE NOTE - IF YOU ARE UNDER THE AGE OF THIRTEEN YEARS, YOU ARE
STRICTLY PROHIBITED FROM ACCESSING OUR SERVICES, AND PROVIDING ANY
PERSONAL INFORMATION TO US. WE DO NOT KNOWINGLY COLLECT ANY
PERSONAL INFORMATION FROM USERS UNDER THE AGE OF THIRTEEN YEARS.
<br><br>
BY CONTINUING TO USE THE SERVICES YOU REPRESENT AND WARRANT TO
THE COMPANY THAT YOU HAVE READ AND UNDERSTOOD THESE TERMS AND
YOU AGREE TO BE BOUND BY THEM.
    
      <br>
      <br>Where you are entering into this Agreement on behalf of an entity, you represent and
warrant to the Company that you have the authority to act on behalf of that entity and to
bind that entity to this Agreement. You also represent and warrant to the Company that
you as well as all your authorized users will use the Service in a manner consistent with
all applicable laws and regulations as well as in compliance with this Agreement.
    </p>
    <h3>6.About the Service</h3>
    <p>
      content by subscribing to channels offered by Creators on Excluzeev. Creators must sign
up for an account on Excluzeev to start one or more channels to provide different
content to their subscribers. Once the Creator uploads the content on a specific channel,
the content will be accessible exclusively to all subscribers of that channel. The Creators
are required to offer a channel description outlining the content that the subscriber will
receive to enable the prospective subscriber in making an informed decision, along with
a timeline of when the content will be released.
<br><br>
The Company does not charge Creators any fees for creating accounts and uploading
content on Excluzeev. However, there is a fixed service fee and transaction fee payable
by Creators on all subscriptions processed through the platform.
<br><br>
The Excluzeev live tool offers live video streaming and chat functionality that enables
Creators to engage with their fans and market the channels to attract new fans. All those
who subscribe to any one or more channels offered by a Creator get access to all
Excluzeevs live broadcast offered by that Creator. <br> <br>

To offer value to subscribers, Creators agree only to offer original content and offer it
exclusively on Excluzeev for the duration of their licensing agreement with the Company.
Any violation of this provision by the Creator will be deemed a material breach of this
Agreement, and the Company may seek appropriate legal remedy.
<br><br>
Please note that the Company only enables content Creators who wish to monetize their
content to offer it to their fans/followers for a subscription fee set by the content Creator.
Nothing in this Agreement guarantees the Creator any particular amount of income or a
minimum number of subscribers during the term of this Agreement. Unless explicitly
stated otherwise, our responsibility is limited to facilitating the availability of the Service
to our Users.    </p>
    <h3>7.Creator’s Obligations</h3>
    <p>By signing up for a Creator account on Excluzeev, you expressly agree that:</p>
    <ul>
      <li>You have the legal right to upload, share, transmit and monetize the content that
you are offering through your account. The Company reserves the right to
remove any content from Excluzeev if we are of the view that such content is
violating any provisions of this Agreement, any applicable law or any other user
or third-party’s lawful rights;</li> <br>
      <li>You will not misrepresent any information that you provide through the Service to
the Company or any other user;</li> <br>
      <li>You will take full responsibility for the accuracy and legality of all content posted/
uploaded or promoted by you or any other party using your account on
Excluzeev;</li> <br>
      <li>You will ensure that your channel offers a detailed and accurate description of
your content to Users;</li> <br>
      <li>You will conduct yourself in a professional manner and in the event of a dispute,
you agree to cooperate in the amicable resolution of such dispute;</li> <br>
      <li>You will promptly and efficiently perform all your obligations towards other Users
and the Company under this Agreement;</li> <br>
      <li>You will ensure that You are aware of any applicable laws and regulations
governing you;</li> <br>
      <li>You will not use any content available on Ecluzeev (whether provided by the
Company, another User or any other third party), on any third party websites or
for other business purposes without Company’s prior written permission;</li> <br>
      <li>You will not post any offensive, obscene, degrading, misleading or harmful text,
video or images on Excluzeev;</li> <br>
      <li>You will be solely responsible for the payment of your taxes owed by you to any
governmental authority arising from any transaction;</li> <br>
      <li>You will not post, upload or in any other way distribute any content that may be
potentially or actually harmful to the Company or any User;</li> <br>
      <li>You will not post, upload or in any other way distribute any content or information
that is false, inaccurate, misleading, fraudulent or deceptive in nature;</li>
    <br>
      <li>You will not, in any way, infringe any User or third party’s copyright, patent,
trademark, trade secret or other proprietary rights or intellectual property rights
including but not limited to rights of publicity, confidentiality or privacy;</li> <br>
      <li>You will not act in any manner that may lead to a violation of any applicable laws
or regulations, including but not limited to those governing export and import
control and trade practices;</li> <br>
      <li>You will not post, upload or share any content that may be deemed defamatory,
libellous or threatening in nature;</li> <br>
<li>
 You will not post, upload or share any content that may be deemed generally
obscene, pornographic, sexually explicit, or contain any material, that we may in
our sole discretion deem inappropriate;
</li>


<br>

      <li>You may not, intentionally or unintentionally cause harm or subvert the function of the Services offered by the Company by introducing any viruses, trojan horses, time bombs, cancelbots or other computer programming routines that may damage, modify, delete or interfere with any system, data or personal information stored on Excluzeev;</li>
     <br> <li>You may not disclose the personal information of any other User on Excluzeev;</li>
   <br>   <li>You will not impersonate another User;</li>
    <br>  <li>You will not post, share or promote any content that is demeaning to any group whether based on race, disability, age, sexual orientation, gender identity or that may be deemed violent, defamatory, suggestive or in any way illegal;</li>
    </ul> <br>
    <p>If we discover that you have violated any of the aforementioned terms, we reserve the right to block your account and take any appropriate legal action to ensure the safety of our users.</p>
    <br>
    <h3>8.Agreement between Users</h3>
    <p>
      By creating a Channel on Excluzeev, you are making an offer to Excluzeev Users to
subscribe to your channel and enter into a Service Agreement with you.

<br><br> <br>
This Agreement is solely between the Creator and Creator’s channel subscribers. The
Company will not be a Party to any such Service Agreements between Creators and
Subscribers. <br> <br>
THE COMPANY WILL NOT BE HELD RESPONSIBLE FOR ANY BREACH OF SUCH
AGREEMENT BY THE SUBSCRIBER OR FOR ANY LOSS OR DAMAGE SUFFERED
BY THE CREATOR AS A RESULT OF SUCH BREACH BY THE SUBSCRIBER. <br> <br>
The Company will not be a party to any disputes between Creators and Subscribers
under any circumstances. <br><br> 
UNLESS EXPRESSLY STATED OTHERWISE THE COMPANY’S RESPONSIBILITY IS
LIMITED TO FACILITATING THE AVAILABILITY OF PLATFORM IN ACCORDANCE
WITH THIS AGREEMENT AND APPLICABLE LAWS. THE COMPANY WILL NOT BE
RESPONSIBLE FOR THE CONDUCT OF ANY USER, WHETHER ONLINE OR
OFFLINE.
    </p>
    <h3>9.Account Setup and Security</h3>
    <p>
      Creators are required to sign up for a creator account on
      <a
        href="https://excluzeev.com/"
      >www.excluzeev.com</a> in order to create channels and offer their content to their fans/community members. We offer one account per Creator, however, a Creator can create multiple channels and offer them at varying subscription rates to his/her fans.
      <br>
      <br>You are required to provide your banking details at the time of account creation which
will enable your subscription payments to be processed and paid into your account less
Company’s service fees and transaction fees. During the account sign up stage you will
be required to provide the Company with certain personal information. You agree to
provide us with true and complete information when requested.
      <br>
      <br> <b>Proof of User Identity:</b> The Company reserves the right to ask for proof of identity to
confirm your age and accuracy of information provided by you during your account
registration. Your failure to present any requested information may result in restriction or
termination of your Account. The Company disclaims all liability for any loss, or damage
incurred by you as a result of termination of your account arising from your failure to
provide proof of your identity. Please note that all your personal information is collected
and processed in accordance with our Privacy Policy. If you do not agree with our
Privacy Policy, please refrain from creating an account on Excluzeev.
      <br>
      <br>Your account is access controlled and as with all access controlled software, the system
relies on the account holder to protect their login credentials. You accept that you are
solely responsible for any activity that occurs on your account and you agree that you
will maintain the confidentiality of your login credentials. Please note that we will never
contact you to request your password or other similar sensitive information and it is your
responsibility to immediately notify us of any such suspicious activity or unauthorized
use of your Creator account.
      <br>
      <br>You may not use another User's account for any purposes whatsoever. You release us
from any liability arising from or related to any unauthorized access to your account. In
the event of any security breach or suspicious activity, you must immediately notify us at
      <a
        href="mailto:privacy@excluzeev.com?subject=Privacy%20Issue"
      >privacy@excluzeev.com</a>.
      <br>
      <br>We reserve the right to immediately suspend or terminate any account if we discover
that you have provided inaccurate, fraudulent or incomplete information to us during your
account registration or anytime thereafter. We also reserve the right to refuse a sign-up
request for a Creator account without providing any reasons for our decision.
    </p>
    <h3>10.Payment and Refunds</h3>
    <p>
      When you sign up as a Creator, you are required to provide us with your banking details
in order to enable our selected payment gateway Stripe to forward the revenue
generated through your Excluzeev channels into your account after deducting our
Service Fee and Transaction Fees. <br><br>
When a User subscribes to one of your channels on Excluzeev, Stripe collects the full
subscription fee from the subscriber each month and transfers the subscription fee less Service Fee (5%) and Transaction fees (2.9% plus C$0.30 per transaction) to the
Creator’s linked account on a fortnightly basis. <br><br>
By accepting these terms and conditions and making use of the Services offered by the
Company, Creators expressly consent to the payment of service fees and transaction
fees as specified in this Agreement. Creators also expressly agree to abide by all
applicable legal terms of Stripe, Inc including those governing chargebacks and refunds
processing. All monetary amounts on Excluzeev and this Agreement are specified in
Canadian Dollars (CAD).
    </p>
    <h3>11.Account Termination</h3>
    <p>
      You may terminate your Excluzeev Creator account at any time by giving the Company a
minimum of 30 days notice. Your account termination notice must be sent to
      <a
        href="mailto:creatortermination@excluzeev.com?subject=Account%20Termination"
      >creatortermination@excluzeev.com</a> with the words “Account Termination” in the subject
line. New fans/followers will no longer be able to subscribe to your channel after you
serve your termination notice but you will remain under obligation to deliver all agreed
content to your current channel subscribers as per your channel description.
Please take note that your data stored on Excluzeev may be retained on the Excluzeev
Service after termination of your Creator account for a period required to fulfil our
business and legal obligations. Notwithstanding the foregoing, the Company may in its
sole discretion choose to delete all your personal data and content upon termination of
your Creator account. Therefore, it is solely your responsibility to ensure that you save
any and all your content/data that you wish to access at a later stage. You will not be
able to reactivate your account at a later stage once your account has been successfully
terminated. The Company reserves the right to terminate this Agreement and your
access to the Service at any time without giving any notice to you, if we find that: <br>
    <ul>
      <li>You have violated the terms of this Agreement</li>
      <li>Your conduct is harmful to the Company or any of its Users</li>
    </ul> <br> <p>We also reserve the right to terminate this Agreement and withdraw our services by giving you 30 days notice.
    </p>
    <h3>12.Your Content</h3>
    <p>
      Excluzeev contains vast amount of user content including user profiles, audio and video
content uploaded by Creators on their channels, content description, public forum chats,
comments etc (“Your Content”). We do not claim any ownership of Your Content, but you
do acknowledge that by uploading, posting and sharing your content you are granting us
exclusive, world-wide, fully paid, royalty-free, license to use, distribute, reproduce,
publish, display or share Your Content on our Services and to make it accessible to other
users in accordance with this Agreement and any other licensing agreement we have
entered into with you as the Creator. <br> <br>
Please note that we reserve the right to remove Your Content from Excluzeev if it is
claimed to be infringing the intellectual property rights of a third-party. If you believe that
Your Content has been wrongly removed from Excluzeev, please contact us to rebut the
copyright infringement claim in accordance with article 14 of this Agreement. For the
purposes of this agreement ‘Your Content’ includes but is not limited to images, audio,
videos, text or similar material. <br> <br>
All information transmitted by a User is the sole responsibility of the User who posted/
listed or shared that content on Excluzeev and the Company will not be liable for any
errors or omissions in Your Content.
    </p>
    <h3>13.Intellectual Property</h3>
    <p>
      Excluding ‘Your Content’, all content and Services made available by the Company
including without limitation, the text, graphics, audio, video, interactive features, code,
marks, software and the like (“Company Content”) are owned by and/or licensed to the
Company and subject to trademark, copyright and other intellectual property rights and
international conventions. This Agreement grants you only a limited, non-exclusive, non-
transferable license to use our Service for your personal and non-commercial use only.
You understand that any violation of this provision can incur criminal as well as civil
liability.
    </p>
    <h3>14.Copyright Disputes Policy</h3>
    <p>
     We respect the Copyrights of others and have a zero tolerance policy towards violations
of copyright laws. The Company reserves the right to immediately terminate your access
to our Service and/or remove any content that we believe, infringes the intellectual
property rights of another person or entity or which is alleged to be infringing the rights of
any third-party. You agree that you will not post, upload, share or in any way reproduce
any content that you do not have the full legal rights to use. If you believe that your
copyrighted material or content is posted, uploaded or made accessible on Excluzeev,
please inform us at the email address listed below of such material and provide us with
the following information:
    </p> <br>
    <ul>
      <li>Identification of the material or content that is claimed to be infringing your
copyrighted works (such as links to the page where such content appears and
description of the content);</li>
      <li>Your contact information including your name, phone number and email address;</li>
      <li>A statement by you setting out that you are either the owner of the copyrighted work or have been authorized by the owner to communicate with us regarding the copyright infringement;</li>
      <li>A statement by you confirming that all information provided by you including your claim is bonafide true.</li> </ul>
      <p style="list-style: none">
        Contact us:
        <a href="mailto:support@excluzeev.com?subject=Support">support@excluzeev.com</a> If you are a Creator and Your Content has been removed as a result of copyright infringement dispute please contact us at the email address provided in this provision along with the following:
      </p>
  
    <ul>
      <li>Information identifying the content that has been wrongly removed with a link to the page where the content was posted before it was removed;</li>
      <li>A statement by you setting out that you are the owner or have the requisite authority or license to use the content that is subject of the Copyright Dispute;</li>
      <li>Any and all supporting evidence that we can provide the disputing party to rebut their claim.</li>
    </ul>
    <br>
    <h3>15.Changes</h3>
    <p>The Company reserves the right to introduce any new features and functionality, modify
existing features, amend any provision of this Agreement as well as the right to
discontinue the Service at our sole discretion. Any changes in features and functionality
of the Service will become effective from the date of implementation. Where we make
any amendments to this Agreement, we will notify you by updating the last updated date
on the top of this Agreement. Please take the time to review these terms regularly to
familiarise yourself with any material changes. You release the Company of any liability
arising from your failure to review such modified Terms.</p>
    <br>
    <h3>16.Anti-Spam Policy</h3>
    <p>You understand that spam is destructive for any online environment and any User
indulging in spammy behaviour on Excluzeev will be immediately banned. We reserve
the right to review and remove any content and restrict any accounts that are flagged by
the Users and remove those users who use Excluzeev for posting unauthorized
advertisements or content that can be deemed spam, posting content with misleading
descriptions, titles or links in order to manipulate Users. Any act of posting repetitive
content will be deemed as spam and we reserve the right to immediately restrict your
access to our Service.</p>
    <br>
    <h3>17.Feedback</h3>
    <p>If you have any ideas or suggestions on how we can improve our Service, you are
welcome to send them to us by email. For purposes of full disclosure and avoidance of
any conflict, please note that by submitting your feedback/ideas to us you are granting
us full and exclusive rights, at our discretion, to use, disclose and otherwise exploit your
ideas and suggestions, either by inclusion in our Service or creation of another business,
in whole or part, without any restriction or compensation to you, either now or ever in
future.</p>
    <b>Contact Us</b>
    <p>
      Email:
      <a href="mailto:feedback@excluzeev.com?subject=feedback">feedback@excluzeev.com</a>
    </p>
    
    <h3>18.Disclaimer of Warranties</h3>
    <p>
      ALL SERVICES PROVIDED BY THE COMPANY ARE PROVIDED TO YOU ON AN “AS
IS”, “WITH ALL FAULTS” AND “AS AVAILABLE” BASIS WITHOUT ANY
REPRESENTATION OF WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. <br><br>
THE COMPANY NEITHER REPRESENT NOR WARRANT THAT THE SERVICE WILL
BE UNINTERRUPTED, ERROR FREE OR COMPLETELY SECURE AND THE ENTIRE
RISK AS TO THE SATISFACTORY QUALITY, PERFORMANCE, ACCURACY AND
EFFORT RESTS WITH YOU. <br><br>
THE COMPANY EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES, EXPRESS,
IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, ACCURACY, TITLE,
NON-INFRINGEMENT. YOU ACCEPT THAT YOUR USE OF THE SERVICES
PROVIDED BY THE COMPANY IS SOLELY AT YOUR OWN RISK. <br><br>
YOU HEREBY EXPRESSLY RELEASE THE COMPANY FROM ANY AND ALL
LIABILITY ARISING FROM YOUR USE OF SERVICES.    </p>
    <h3>19.Limitation of Liability</h3>
    <p>
      IN NO EVENT SHALL THE COMPANY BE HELD LIABLE FOR ANY INDIRECT,
CONSEQUENTIAL, SPECIAL, INCIDENTAL OR PUNITIVE DAMAGES ARISING OUT
OF OR ASSOCIATED WITH THE USE OF THE SERVICES. THE ABOVE LIMITATION
OF LIABILITY SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY
APPLICABLE LAW REGARDLESS OF WHETHER THE DAMAGES AROSE FROM
BREACH OF CONTRACT, NEGLIGENCE OR ANY OTHER CAUSE OF ACTION. <br><br>
UNDER NO CIRCUMSTANCES SHALL THE LIABILITY OF THE COMPANY EXCEED
THE AMOUNT PAID BY YOU TO THE COMPANY IN SERVICE FEES IN THE THREE
MONTH PERIOD WHEN THE ISSUE FIRST AROSE. <br><br>
THE COMPANY MAKES NO REPRESENTATION REGARDING THE SUITABILITY OR
AVAILABILITY OF THE SERVICES IN LOCATIONS OTHER THAN THOSE LISTED ON
OUR WEBSITE.
    </p>
    <h3>20.Indemnity</h3>
    <p>
      You agree to release, defend, indemnify, and hold harmless the Company, its founders, affiliates, subsidiaries against any claims, liabilities, charges, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with:
      <br>(i) the violation of these Terms by you,
     <br> <br>(ii) Your gross negligence or willful misconduct, or
     <br> <br>(iii) the infringement by you, or any third party using your Account, of any intellectual property or other right of any person or entity.
    </p>
    <h3>21.Governing Law and Jurisdiction</h3>
    <p>TThis Agreement shall be construed in accordance with the provincial laws of Alberta and
national laws of Canada. Any action or claims brought against the Company must be
brought in a court of law with appropriate jurisdiction to rule upon the matter sitting in
Edmonton.</p>
    
    <h3>22.Severability</h3>
    <p>If for any reason, any provision of this Agreement or any part of any provision is deemed
to be unlawful, void, or for any reason unenforceable, then such provision will be limited
or eliminated from this Agreement only to the extent necessary and will not affect the
validity and enforceability of any remaining provisions.</p>
    <h3>23.Force Majeure</h3>
    <p>Neither the Company nor the User will be held liable for failure to perform any of their
obligations towards the other if such failure is as a result of a force majeure event or acts
of God (including fire, flood, earthquake, storm, hurricane or other natural disaster), war,
invasion, act of foreign enemies, hostilities (regardless of whether war is declared), civil
war, rebellion, revolution, insurrection, military or usurped power or confiscation, terrorist
activities, nationalisation, government sanction, blockage, embargo, labor dispute, strike,
lockout or any interruption or any failure of electricity or server, system, computer,
internet or telephone service. Whilst the performance has been suspended for more than
14 days, either the Company or the User may terminate this agreement by immediate
written notice.</p>
  </v-container>
</template>

<script>
export default {
  name: "ContentCreator"
};
</script>

<style scoped>
.content {
  text-align: justify;
  font-family: Arial;
  margin: 30px;
  padding: 35px;
}
.main_text {
  text-align: center;
}
p {
  font-size: 16px;
}
</style>
